python scripts/generate_stimuli/generate_faces.py \
    --out-dir /analyse/Project0257/lukas/data/fewIDmanyIMG2 \
    --n-id 128 \
    --n-var 1024 \
    --genders M \
    --ethns WC \
    --ages 25 25 \
    --x-rot -30 30 \
    --y-rot -30 30 \
    --z-rot -30 30 \
    --x-rot-lights -30 30 \
    --y-rot-lights -30 30 \
    --save-id-params \
    --save-image-separately \
    --camera-distance 300 \
    --add-background \
    --save-background